// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempProject.Models;

#nullable disable

namespace TempProject.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TempProject.Models.Accident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccidentCausesId")
                        .HasColumnType("int");

                    b.Property<string>("AccidentLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassificationOfAccidentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfEvent")
                        .HasColumnType("date");

                    b.Property<string>("DescriptionOfTheEvent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectCauses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrillerCode")
                        .HasColumnType("int");

                    b.Property<string>("DrillerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrillerPositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InjuredPersonCode")
                        .HasColumnType("int");

                    b.Property<string>("InjuredPersonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InjuredPersonPositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PreventionCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("PusherCode")
                        .HasColumnType("int");

                    b.Property<string>("PusherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PusherPositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QHSEEmpCode")
                        .HasColumnType("int");

                    b.Property<string>("QHSEEmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QHSEPositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.Property<string>("RootCauses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeOfEvent")
                        .HasColumnType("time");

                    b.Property<int>("TypeOfInjuryID")
                        .HasColumnType("int");

                    b.Property<int>("ViolationCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccidentCausesId");

                    b.HasIndex("ClassificationOfAccidentId");

                    b.HasIndex("PreventionCategoryId");

                    b.HasIndex("RigId");

                    b.HasIndex("TypeOfInjuryID");

                    b.HasIndex("ViolationCategoryId");

                    b.HasIndex("userID");

                    b.ToTable("Accidents");
                });

            modelBuilder.Entity("TempProject.Models.AccidentCauses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccidentCauses");
                });

            modelBuilder.Entity("TempProject.Models.AccidentImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccidentId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccidentId");

                    b.ToTable("AccidentImages");
                });

            modelBuilder.Entity("TempProject.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("No")
                        .HasColumnType("int");

                    b.Property<int>("PTSMId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PTSMId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("TempProject.Models.BOP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Catering")
                        .HasColumnType("int");

                    b.Property<int>("Client")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ECDC")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ManPower")
                        .HasColumnType("int");

                    b.Property<int>("Other")
                        .HasColumnType("int");

                    b.Property<int>("Rental")
                        .HasColumnType("int");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.Property<int>("TotalManHours")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Visitors")
                        .HasColumnType("int");

                    b.Property<int>("WatchMen")
                        .HasColumnType("int");

                    b.Property<int>("inspection")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RigId");

                    b.HasIndex("UserId");

                    b.ToTable("Bop");
                });

            modelBuilder.Entity("TempProject.Models.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("TempProject.Models.ClassificationOfAccident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClassificationOfAccidents");
                });

            modelBuilder.Entity("TempProject.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("TempProject.Models.ComminucationMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComminucationMethods");
                });

            modelBuilder.Entity("TempProject.Models.Crew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CrewName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("TempProject.Models.CrewQuizAndQHSEDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrewId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QHSEDailyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.HasIndex("QHSEDailyId");

                    b.ToTable("CrewQuizAndQHSEDaily");
                });

            modelBuilder.Entity("TempProject.Models.CrewSaftyAlertAndQHSEDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrewId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QHSEDailyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.HasIndex("QHSEDailyId");

                    b.ToTable("CrewSaftyAlertAndQHSEDaily");
                });

            modelBuilder.Entity("TempProject.Models.DaysSinceNoLTI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RigId");

                    b.ToTable("DaysSinceNoLTI");
                });

            modelBuilder.Entity("TempProject.Models.Drill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DeficienciesPoints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrillScenario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrillTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectivenessPoints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyEquipmentUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QHSEEmpCode")
                        .HasColumnType("int");

                    b.Property<string>("QHSEEmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QHSEPositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.Property<int>("STPCode")
                        .HasColumnType("int");

                    b.Property<string>("STPName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STPPositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeCompleted")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeInitiated")
                        .HasColumnType("time");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DrillTypeId");

                    b.HasIndex("RigId");

                    b.HasIndex("userID");

                    b.ToTable("Drills");
                });

            modelBuilder.Entity("TempProject.Models.DrillImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.ToTable("DrillImages");
                });

            modelBuilder.Entity("TempProject.Models.DrillType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DrillTypes");
                });

            modelBuilder.Entity("TempProject.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LicenceExpireData")
                        .HasColumnType("date");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverNames");
                });

            modelBuilder.Entity("TempProject.Models.EmergencyResponseTeamMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("TeamMemberCode")
                        .HasColumnType("int");

                    b.Property<string>("TeamMemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMemberPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.ToTable("EmergencyResponseTeamMembers");
                });

            modelBuilder.Entity("TempProject.Models.EmpCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("RigId");

                    b.ToTable("EmpCodes");
                });

            modelBuilder.Entity("TempProject.Models.EmployeeCompetencyEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeCode")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeePositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QHSEEmpCode")
                        .HasColumnType("int");

                    b.Property<string>("QHSEEmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QHSEPositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RigId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("userID");

                    b.ToTable("EmployeeCompetencyEvaluation");
                });

            modelBuilder.Entity("TempProject.Models.HazardImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PotentialHazardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PotentialHazardId");

                    b.ToTable("HazardImages");
                });

            modelBuilder.Entity("TempProject.Models.JMP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ArrivalStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CommunicationID")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<int>("DriverNameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnterTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstimatedArriveDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("EstimatedArriveTime")
                        .HasColumnType("time");

                    b.Property<string>("InspectionVechile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JournyManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JournyNumber")
                        .HasColumnType("int");

                    b.Property<string>("ManagerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NightDrivingReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeOfJourny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QHSEManagerMustApprove")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReachBeforeDark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestLocationNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouteNameID")
                        .HasColumnType("int");

                    b.Property<double>("SpeedLimit")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("notifyStatus")
                        .HasColumnType("int");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationID");

                    b.HasIndex("DriverNameId");

                    b.HasIndex("RouteNameID");

                    b.HasIndex("VehicleId");

                    b.HasIndex("userID");

                    b.ToTable("JMPs");
                });

            modelBuilder.Entity("TempProject.Models.JMP_Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JMPID")
                        .HasColumnType("int");

                    b.Property<int>("PassengerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JMPID");

                    b.HasIndex("PassengerID");

                    b.ToTable("JMP_Passengers");
                });

            modelBuilder.Entity("TempProject.Models.LTIPrevDateAndDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysSinceNoLTIId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PrevDate")
                        .HasColumnType("date");

                    b.Property<int>("PrevDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DaysSinceNoLTIId");

                    b.ToTable("LTIPrevDateAndDays");
                });

            modelBuilder.Entity("TempProject.Models.LeaderShipVisitsAndQHSEDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeadershipVisitId")
                        .HasColumnType("int");

                    b.Property<int>("QHSEDailyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeadershipVisitId");

                    b.HasIndex("QHSEDailyId");

                    b.ToTable("LeaderShipVisitsAndQHSEDaily");
                });

            modelBuilder.Entity("TempProject.Models.LeadershipVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LeadershipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadershipVisits");
                });

            modelBuilder.Entity("TempProject.Models.NonRecordableAccident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NonRecordableAccidents");
                });

            modelBuilder.Entity("TempProject.Models.PPE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PPEs");
                });

            modelBuilder.Entity("TempProject.Models.PPEAndPPEReceiving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PPEId")
                        .HasColumnType("int");

                    b.Property<int>("PPEReceivingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PPEId");

                    b.HasIndex("PPEReceivingId");

                    b.ToTable("PPEAndPPEReceivings");
                });

            modelBuilder.Entity("TempProject.Models.PPEReceiving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeCode")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeePositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NormalCoverallsSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QHSEEmpCode")
                        .HasColumnType("int");

                    b.Property<string>("QHSEEmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QHSEPositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.Property<string>("SafetyBootsSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThermalCoverallsSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RigId");

                    b.HasIndex("userID");

                    b.ToTable("PPEReceivings");
                });

            modelBuilder.Entity("TempProject.Models.PTSM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NumsofTrainees")
                        .HasColumnType("int");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RigId");

                    b.HasIndex("UserId");

                    b.ToTable("PTSMs");
                });

            modelBuilder.Entity("TempProject.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("TempProject.Models.Positions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("TempProject.Models.PotentialHazard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NeededAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PO_No")
                        .HasColumnType("int");

                    b.Property<DateTime>("PR_IssueDate")
                        .HasColumnType("date");

                    b.Property<int>("PR_No")
                        .HasColumnType("int");

                    b.Property<int>("ResponibilityId")
                        .HasColumnType("int");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ResponibilityId");

                    b.HasIndex("RigId");

                    b.HasIndex("userID");

                    b.ToTable("PotentialHazard");
                });

            modelBuilder.Entity("TempProject.Models.PreventionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PreventionCategorys");
                });

            modelBuilder.Entity("TempProject.Models.ProblemFacedDuringRigMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendationProblemRepeated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RigMovePerformanceId")
                        .HasColumnType("int");

                    b.Property<double>("TimeLostProblem")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RigMovePerformanceId");

                    b.ToTable("ProblemFacedDuringRigMoves");
                });

            modelBuilder.Entity("TempProject.Models.QHSEDailyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DaysSinceLastLTI")
                        .HasColumnType("int");

                    b.Property<int>("DaysSinceNoLTIId")
                        .HasColumnType("int");

                    b.Property<int>("DrillsRecords")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ManPowerNumber")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyInspection")
                        .HasColumnType("int");

                    b.Property<int>("NonRecordableAccident")
                        .HasColumnType("int");

                    b.Property<int>("PTSMRecords")
                        .HasColumnType("int");

                    b.Property<int>("PTWCold")
                        .HasColumnType("int");

                    b.Property<int>("PTWHot")
                        .HasColumnType("int");

                    b.Property<int>("QuizCrewNumber")
                        .HasColumnType("int");

                    b.Property<int>("RecordableAccident")
                        .HasColumnType("int");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.Property<int>("RigTrackingClosedPoints")
                        .HasColumnType("int");

                    b.Property<int>("RigTrackingOpenPoints")
                        .HasColumnType("int");

                    b.Property<int>("RigVehiclesKilometers")
                        .HasColumnType("int");

                    b.Property<int>("SafetyAlertCrewNumber")
                        .HasColumnType("int");

                    b.Property<int>("SafetyInduction")
                        .HasColumnType("int");

                    b.Property<int>("StopCardsRecords")
                        .HasColumnType("int");

                    b.Property<int>("TotalManPowerHours")
                        .HasColumnType("int");

                    b.Property<int>("TotalPTW")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WallName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeeklyInspection")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DaysSinceNoLTIId");

                    b.HasIndex("RigId");

                    b.HasIndex("UserId");

                    b.ToTable("QHSEDailyReport");
                });

            modelBuilder.Entity("TempProject.Models.RecordableAccident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RecordableAccidents");
                });

            modelBuilder.Entity("TempProject.Models.ReportedByName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReportedByNames");
                });

            modelBuilder.Entity("TempProject.Models.ReportedByPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReportedByPositions");
                });

            modelBuilder.Entity("TempProject.Models.Responsibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Responsibility");
                });

            modelBuilder.Entity("TempProject.Models.Rig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rigs");
                });

            modelBuilder.Entity("TempProject.Models.RigMovePerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptanceDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("AcceptanceTime")
                        .HasColumnType("time");

                    b.Property<double>("ActualMoveTime")
                        .HasColumnType("float");

                    b.Property<double>("BudgetTargetTotalDay")
                        .HasColumnType("float");

                    b.Property<double>("BudgetTargetTotalMoney")
                        .HasColumnType("float");

                    b.Property<double>("DieselConsumed")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("MoveDistance")
                        .HasColumnType("float");

                    b.Property<string>("NewWellName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldWellName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("ReleaseTime")
                        .HasColumnType("time");

                    b.Property<int>("RigId")
                        .HasColumnType("int");

                    b.Property<string>("TargetArchived")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RigId");

                    b.HasIndex("UserId");

                    b.ToTable("RigMovePerformances");
                });

            modelBuilder.Entity("TempProject.Models.RouteName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RouteNames");
                });

            modelBuilder.Entity("TempProject.Models.StopCardRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionRequired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassificationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReportedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedByPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopWorkAuthorityApplied")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfObservationCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationID");

                    b.HasIndex("TypeOfObservationCategoryID");

                    b.HasIndex("userID");

                    b.ToTable("StopCardRegisters");
                });

            modelBuilder.Entity("TempProject.Models.SubjectList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubjectList");
                });

            modelBuilder.Entity("TempProject.Models.TypeOfInjury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfInjurys");
                });

            modelBuilder.Entity("TempProject.Models.TypeOfObservationCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfObservationCategorys");
                });

            modelBuilder.Entity("TempProject.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LicenceExpireData")
                        .HasColumnType("date");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassengerNumber")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("TempProject.Models.ViolationCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ViolationCategorys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TempProject.Models.Accident", b =>
                {
                    b.HasOne("TempProject.Models.AccidentCauses", "AccidentCauses")
                        .WithMany("Accidents")
                        .HasForeignKey("AccidentCausesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.ClassificationOfAccident", "ClassificationOfAccident")
                        .WithMany("Accidents")
                        .HasForeignKey("ClassificationOfAccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.PreventionCategory", "PreventionCategory")
                        .WithMany("Accidents")
                        .HasForeignKey("PreventionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany("Accidents")
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.TypeOfInjury", "TypeOfInjury")
                        .WithMany("Accidents")
                        .HasForeignKey("TypeOfInjuryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.ViolationCategory", "ViolationCategory")
                        .WithMany("Accidents")
                        .HasForeignKey("ViolationCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccidentCauses");

                    b.Navigation("ClassificationOfAccident");

                    b.Navigation("PreventionCategory");

                    b.Navigation("Rig");

                    b.Navigation("TypeOfInjury");

                    b.Navigation("ViolationCategory");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TempProject.Models.AccidentImages", b =>
                {
                    b.HasOne("TempProject.Models.Accident", "Accident")
                        .WithMany("Images")
                        .HasForeignKey("AccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("TempProject.Models.Attendance", b =>
                {
                    b.HasOne("TempProject.Models.PTSM", "PTSM")
                        .WithMany("Attendances")
                        .HasForeignKey("PTSMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PTSM");
                });

            modelBuilder.Entity("TempProject.Models.BOP", b =>
                {
                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany()
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rig");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TempProject.Models.CrewQuizAndQHSEDaily", b =>
                {
                    b.HasOne("TempProject.Models.Crew", "Crew")
                        .WithMany("CrewQuizAndQHSEDaily")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.QHSEDailyReport", "QHSEDaily")
                        .WithMany("CrewQuizAndQHSEDaily")
                        .HasForeignKey("QHSEDailyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("QHSEDaily");
                });

            modelBuilder.Entity("TempProject.Models.CrewSaftyAlertAndQHSEDaily", b =>
                {
                    b.HasOne("TempProject.Models.Crew", "Crew")
                        .WithMany("CrewSaftyAlertAndQHSEDaily")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.QHSEDailyReport", "QHSEDaily")
                        .WithMany("CrewSaftyAlertAndQHSEDaily")
                        .HasForeignKey("QHSEDailyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("QHSEDaily");
                });

            modelBuilder.Entity("TempProject.Models.DaysSinceNoLTI", b =>
                {
                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany("DaysSinceNoLTI")
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rig");
                });

            modelBuilder.Entity("TempProject.Models.Drill", b =>
                {
                    b.HasOne("TempProject.Models.DrillType", "DrillType")
                        .WithMany("Drills")
                        .HasForeignKey("DrillTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany()
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrillType");

                    b.Navigation("Rig");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TempProject.Models.DrillImages", b =>
                {
                    b.HasOne("TempProject.Models.Drill", "Drill")
                        .WithMany("Images")
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");
                });

            modelBuilder.Entity("TempProject.Models.EmergencyResponseTeamMembers", b =>
                {
                    b.HasOne("TempProject.Models.Drill", "Drill")
                        .WithMany("emergencyResponseTeamMembers")
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");
                });

            modelBuilder.Entity("TempProject.Models.EmpCode", b =>
                {
                    b.HasOne("TempProject.Models.Positions", "Positions")
                        .WithMany("EmpCodes")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany("EmpCode")
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Positions");

                    b.Navigation("Rig");
                });

            modelBuilder.Entity("TempProject.Models.EmployeeCompetencyEvaluation", b =>
                {
                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany("RigEmployeeCompetencyEvaluation")
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.SubjectList", "Subjectlist")
                        .WithMany("EmployeeCompetencyEvaluation")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rig");

                    b.Navigation("Subjectlist");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TempProject.Models.HazardImages", b =>
                {
                    b.HasOne("TempProject.Models.PotentialHazard", "PotentialHazard")
                        .WithMany("Images")
                        .HasForeignKey("PotentialHazardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PotentialHazard");
                });

            modelBuilder.Entity("TempProject.Models.JMP", b =>
                {
                    b.HasOne("TempProject.Models.ComminucationMethod", "comminucationMethod")
                        .WithMany("JMPs")
                        .HasForeignKey("CommunicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.Driver", "DriverName")
                        .WithMany("JMPs")
                        .HasForeignKey("DriverNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.RouteName", "RouteName")
                        .WithMany("JMPs")
                        .HasForeignKey("RouteNameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.Vehicle", "Vehicle")
                        .WithMany("JMPs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverName");

                    b.Navigation("RouteName");

                    b.Navigation("Vehicle");

                    b.Navigation("comminucationMethod");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TempProject.Models.JMP_Passenger", b =>
                {
                    b.HasOne("TempProject.Models.JMP", "JMP")
                        .WithMany("jMP_Passengers")
                        .HasForeignKey("JMPID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.Passenger", "Passenger")
                        .WithMany("jMP_Passengers")
                        .HasForeignKey("PassengerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JMP");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("TempProject.Models.LTIPrevDateAndDays", b =>
                {
                    b.HasOne("TempProject.Models.DaysSinceNoLTI", "DaysSinceNoLTI")
                        .WithMany("LTIPrevDateAndDays")
                        .HasForeignKey("DaysSinceNoLTIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaysSinceNoLTI");
                });

            modelBuilder.Entity("TempProject.Models.LeaderShipVisitsAndQHSEDaily", b =>
                {
                    b.HasOne("TempProject.Models.LeadershipVisit", "LeadershipVisit")
                        .WithMany("LeaderShipVisitsAndQHSEDaily")
                        .HasForeignKey("LeadershipVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.QHSEDailyReport", "QHSEDaily")
                        .WithMany("LeaderShipVisitsAndQHSEDaily")
                        .HasForeignKey("QHSEDailyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeadershipVisit");

                    b.Navigation("QHSEDaily");
                });

            modelBuilder.Entity("TempProject.Models.PPEAndPPEReceiving", b =>
                {
                    b.HasOne("TempProject.Models.PPE", "PPE")
                        .WithMany("PPEAndPPEReceiving")
                        .HasForeignKey("PPEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.PPEReceiving", "PPEReceiving")
                        .WithMany("PPEAndPPEReceiving")
                        .HasForeignKey("PPEReceivingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PPE");

                    b.Navigation("PPEReceiving");
                });

            modelBuilder.Entity("TempProject.Models.PPEReceiving", b =>
                {
                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany("PPEReceiving")
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TempProject.Models.PTSM", b =>
                {
                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany()
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rig");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TempProject.Models.PotentialHazard", b =>
                {
                    b.HasOne("TempProject.Models.Responsibility", "Responsibility")
                        .WithMany("Hazards")
                        .HasForeignKey("ResponibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany("PotentialHazard")
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsibility");

                    b.Navigation("Rig");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TempProject.Models.ProblemFacedDuringRigMove", b =>
                {
                    b.HasOne("TempProject.Models.RigMovePerformance", "RigMovePerformance")
                        .WithMany("problemFacedDuringRigMoves")
                        .HasForeignKey("RigMovePerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RigMovePerformance");
                });

            modelBuilder.Entity("TempProject.Models.QHSEDailyReport", b =>
                {
                    b.HasOne("TempProject.Models.Client", "Client")
                        .WithMany("QHSEDailyReport")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.DaysSinceNoLTI", "DaysSinceNoLTI")
                        .WithMany("QHSEDailyReport")
                        .HasForeignKey("DaysSinceNoLTIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany("QHSEDailyReport")
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DaysSinceNoLTI");

                    b.Navigation("Rig");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TempProject.Models.RigMovePerformance", b =>
                {
                    b.HasOne("TempProject.Models.Rig", "Rig")
                        .WithMany("RigMovePerformances")
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rig");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TempProject.Models.StopCardRegister", b =>
                {
                    b.HasOne("TempProject.Models.Classification", "Classification")
                        .WithMany("StopCardRegisters")
                        .HasForeignKey("ClassificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempProject.Models.TypeOfObservationCategory", "TypeOfObservationCategory")
                        .WithMany("StopCardRegisters")
                        .HasForeignKey("TypeOfObservationCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classification");

                    b.Navigation("TypeOfObservationCategory");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TempProject.Models.Accident", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TempProject.Models.AccidentCauses", b =>
                {
                    b.Navigation("Accidents");
                });

            modelBuilder.Entity("TempProject.Models.Classification", b =>
                {
                    b.Navigation("StopCardRegisters");
                });

            modelBuilder.Entity("TempProject.Models.ClassificationOfAccident", b =>
                {
                    b.Navigation("Accidents");
                });

            modelBuilder.Entity("TempProject.Models.Client", b =>
                {
                    b.Navigation("QHSEDailyReport");
                });

            modelBuilder.Entity("TempProject.Models.ComminucationMethod", b =>
                {
                    b.Navigation("JMPs");
                });

            modelBuilder.Entity("TempProject.Models.Crew", b =>
                {
                    b.Navigation("CrewQuizAndQHSEDaily");

                    b.Navigation("CrewSaftyAlertAndQHSEDaily");
                });

            modelBuilder.Entity("TempProject.Models.DaysSinceNoLTI", b =>
                {
                    b.Navigation("LTIPrevDateAndDays");

                    b.Navigation("QHSEDailyReport");
                });

            modelBuilder.Entity("TempProject.Models.Drill", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("emergencyResponseTeamMembers");
                });

            modelBuilder.Entity("TempProject.Models.DrillType", b =>
                {
                    b.Navigation("Drills");
                });

            modelBuilder.Entity("TempProject.Models.Driver", b =>
                {
                    b.Navigation("JMPs");
                });

            modelBuilder.Entity("TempProject.Models.JMP", b =>
                {
                    b.Navigation("jMP_Passengers");
                });

            modelBuilder.Entity("TempProject.Models.LeadershipVisit", b =>
                {
                    b.Navigation("LeaderShipVisitsAndQHSEDaily");
                });

            modelBuilder.Entity("TempProject.Models.PPE", b =>
                {
                    b.Navigation("PPEAndPPEReceiving");
                });

            modelBuilder.Entity("TempProject.Models.PPEReceiving", b =>
                {
                    b.Navigation("PPEAndPPEReceiving");
                });

            modelBuilder.Entity("TempProject.Models.PTSM", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("TempProject.Models.Passenger", b =>
                {
                    b.Navigation("jMP_Passengers");
                });

            modelBuilder.Entity("TempProject.Models.Positions", b =>
                {
                    b.Navigation("EmpCodes");
                });

            modelBuilder.Entity("TempProject.Models.PotentialHazard", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TempProject.Models.PreventionCategory", b =>
                {
                    b.Navigation("Accidents");
                });

            modelBuilder.Entity("TempProject.Models.QHSEDailyReport", b =>
                {
                    b.Navigation("CrewQuizAndQHSEDaily");

                    b.Navigation("CrewSaftyAlertAndQHSEDaily");

                    b.Navigation("LeaderShipVisitsAndQHSEDaily");
                });

            modelBuilder.Entity("TempProject.Models.Responsibility", b =>
                {
                    b.Navigation("Hazards");
                });

            modelBuilder.Entity("TempProject.Models.Rig", b =>
                {
                    b.Navigation("Accidents");

                    b.Navigation("DaysSinceNoLTI");

                    b.Navigation("EmpCode");

                    b.Navigation("PPEReceiving");

                    b.Navigation("PotentialHazard");

                    b.Navigation("QHSEDailyReport");

                    b.Navigation("RigEmployeeCompetencyEvaluation");

                    b.Navigation("RigMovePerformances");
                });

            modelBuilder.Entity("TempProject.Models.RigMovePerformance", b =>
                {
                    b.Navigation("problemFacedDuringRigMoves");
                });

            modelBuilder.Entity("TempProject.Models.RouteName", b =>
                {
                    b.Navigation("JMPs");
                });

            modelBuilder.Entity("TempProject.Models.SubjectList", b =>
                {
                    b.Navigation("EmployeeCompetencyEvaluation");
                });

            modelBuilder.Entity("TempProject.Models.TypeOfInjury", b =>
                {
                    b.Navigation("Accidents");
                });

            modelBuilder.Entity("TempProject.Models.TypeOfObservationCategory", b =>
                {
                    b.Navigation("StopCardRegisters");
                });

            modelBuilder.Entity("TempProject.Models.Vehicle", b =>
                {
                    b.Navigation("JMPs");
                });

            modelBuilder.Entity("TempProject.Models.ViolationCategory", b =>
                {
                    b.Navigation("Accidents");
                });
#pragma warning restore 612, 618
        }
    }
}
